---
# This playbook deploys all sub playbooks

- name: apply common configuration to all nodes
  hosts: mregan-dev
  user: root

  roles:
    - common
    - search_head
  
  vars:
    splunk_binary: 'splunk-6.1.1-207789-linux-2.6-amd64.deb'
