---
# This playbook install the apps required in a server

- name: install security controls
  tags:
   - configuration
   - security
  apt: name={{ item }} state=present
  with_items:
   - chkrootkit
   - rkhunter
   - clamav
   - fail2ban

- name: install basic utilities
  tags:
   - configuration
  apt: name={{ item }} state=present
  with_items:
   - vim
   - screen
   - iotop
   - htop
   - ioping
   - ntp

